In [3]:
import numpy as np
import pandas as pd
import os
import pickle
import seaborn as sns
from pycaret.regression import *

In [24]:
data = pd.read_csv("distances_Tpeak_temporal_ind_24102023_wide.csv")
data = data[(data["FlashType"] == 1) | (data["FlashType"] == 2)]
data = data.drop(["participant_id","correct", "rt","correct_abs", "rt_abs", "rt_Cod","rt_rel", "bl_correct","bl_rt", "CFF"], axis=1, index=None)
num_features = data.columns[4:].to_list()
# ord_features = [data_flash1.columns[0]]
cat_features = ['FlashType', 'NrBeeps', 'sex']

In [25]:
num_features

['age',
 'Dist to A1, LH',
 'Dist to A1, RH',
 'Dist to V1, LH',
 'Dist to V1, RH',
 'dist_ratio_L',
 'dist_ratio_R']

In [26]:
cat_features

['FlashType', 'NrBeeps', 'sex']

In [28]:
setup(data, target = 'correct_rel', session_id=123, normalize = True, ordinal_features = None, numeric_features = num_features, categorical_features = cat_features)

In [29]:
# compare baseline models
best = compare_models()